server:
  port: 8092

spring:
  application:
    name: user
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/user_service_db
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification-welcome-email: notification.welcome.email.queue
  routing-keys:
    internal-notification: internal.notification.routing-key